### ISSUE TITLE
Publish to Chrome Store

### ISSUE THREAD

**Issue by rickyvetter** [socialtables/chrome-cheers#3]
@mcwhittemore any thoughts on how to publish this? Under ST? Under ST Engineering might be better - so it doesn't get thrown in with possible ST extensions in the future. Or personal account. I'm fine with whichever makes the most sense.

**Comment by mcwhittemore** [comment]
Lets publish it via ST Engineering!

**Comment by rickyvetter** [comment]
Should we use eng@socialtables.com as the developer email? We would all get emails - which may be undesirable. If so - can we get signed up here? https://chrome.google.com/webstore/developer/dashboard

**Comment by mcwhittemore** [comment]
Good with me.
